import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
// import { motion } from "framer-motion";
import DarkModeButton from "../components/DarkModeButton";
import IconButton from "../components/IconButton";
import { DribbbleIcon } from "../icons/DribbbleIcon";

import ".";
import { Button } from "../components/Button";

const LP: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    // <div className="relative flex flex-col-reverse items-center overflow-hidden bg-[#E0E5FF] dark:bg-[#000214]">
    <div className="relative flex flex-col-reverse items-center overflow-hidden ">
      {/* <motion.div className="absolute -right-12 h-96 w-96 bg-blue-500" /> */}

      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center gap-4 p-4">
        <DarkModeButton></DarkModeButton>

        <div className="card">
          <div className="body">
            <div className="history"></div>
          </div>
          npm install @radix-ui/react-select
        </div>

        <h1 className="text-5xl font-extrabold leading-normal text-blue-600 dark:text-orange-600 md:text-[5rem]">
          Create <span className="text-purple-500">T3</span> App
        </h1>

        <Button intent="primary">I am a button</Button>

        {/* <div className="flex w-full flex-col items-center justify-center gap-4 pt-6 text-2xl text-blue-600 dark:text-orange-600">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div> */}
      </main>
    </div>
  );
};

// function setTheme(name: string) {
//   localStorage.setItem("theme", name);
//   document.documentElement.className = name;
// }

// function toggleTheme() {
//   if (
//     typeof window !== "undefined" &&
//     localStorage.getItem("theme") === "dark-theme"
//   ) {
//     setTheme("light-theme");
//   } else {
//     setTheme("dark-theme");
//   }
// }

// (function () {
//   if (localStorage.getItem("theme") === "dark-theme") {
//     setTheme("dark-theme");
//   } else {
//     setTheme("light-theme");
//   }
// })();

export default LP;
